<?php
/*
 Template Name: Vieproxy Single Blog Post
*/
?>
<?php get_header(); ?>

<?php

function vp_single_read_time($post_id)
{
    $content = get_post_field('post_content', $post_id);
    $word_count = str_word_count(strip_tags($content));
    $minutes = max(1, round($word_count / 200));
    return $minutes . ' phút đọc';
}

// Chạy loop để lấy post hiện tại
if (have_posts()):
    while (have_posts()):
        the_post();

        $post_id = get_the_ID();
        $post_title = get_the_title();
        $post_date = get_the_date('j \t\h\á\n\g n, Y');
        $author_name = get_the_author();
        $author_id = get_the_author_meta('ID');
        $author_bio = get_the_author_meta('description');
        $author_url = get_author_posts_url($author_id);
        $read_time = vp_single_read_time($post_id);

        // Author avatar
        $author_avatar = get_avatar_url($author_id, ['size' => 80]);

        // Author post count
        $author_post_count = count_user_posts($author_id, 'post');

        // Author join date
        $author_registered = get_the_author_meta('user_registered');
        $author_joined = date_i18n('M Y', strtotime($author_registered));

        // Categories
        $post_cats = get_the_category();
        $cat_name = !empty($post_cats) ? $post_cats[0]->name : '';
        $cat_url = !empty($post_cats) ? get_category_link($post_cats[0]->term_id) : '';

        // FAQ từ ACF 
        $faqs = [];
        if (function_exists('get_field')) {
            $faqs = get_field('faqs', $post_id) ?: [];
        }

        // Related posts 
        $related_args = [
            'post_type' => 'post',
            'posts_per_page' => 3,
            'post_status' => 'publish',
            'post__not_in' => [$post_id],
            'orderby' => 'date',
            'order' => 'DESC',
        ];
        if (!empty($post_cats)) {
            $related_args['category__in'] = [$post_cats[0]->term_id];
        }
        $related_query = new WP_Query($related_args);
        ?>

<!-- ══════════════════════════════════════════
     SINGLE ARTICLE
══════════════════════════════════════════ -->
<section class="single-blog-section">
    <div class="wrapper">
        <div class="single-blog-container">

            <!-- ── LEFT: TOC Sidebar ── -->
            <aside class="single-blog-toc-sidebar">
                <div class="single-blog-toc" id="tocBox">
                    <div class="single-blog-toc__title">
                        <i class="fa-solid fa-list" style="color:#007bf3"></i>
                        Mục lục
                    </div>
                    <ul class="single-blog-toc__list" id="tocList">
                        <!-- Auto-generated by JS từ H2/H3 trong article -->
                    </ul>
                </div>
            </aside>

            <!-- ── RIGHT: Article ── -->
            <article class="single-blog-article" id="singleArticle">

                <!-- Breadcrumb -->
                <nav class="single-blog-breadcrumb" aria-label="breadcrumb">
                    <a href="<?php echo esc_url(home_url('/')); ?>" class="breadcrumb-link">Trang chủ</a>
                    <span class="breadcrumb-sep"><i class="fa-solid fa-chevron-right"></i></span>
                    <a href="<?php echo esc_url(get_permalink(get_option('page_for_posts'))); ?>"
                        class="breadcrumb-link">Blog</a>
                    <?php if (!empty($cat_name)): ?>
                    <span class="breadcrumb-sep"><i class="fa-solid fa-chevron-right"></i></span>
                    <a href="<?php echo esc_url($cat_url); ?>"
                        class="breadcrumb-link"><?php echo esc_html($cat_name); ?></a>
                    <?php endif; ?>
                    <span class="breadcrumb-sep"><i class="fa-solid fa-chevron-right"></i></span>
                    <span
                        class="breadcrumb-current"><?php echo esc_html(wp_trim_words($post_title, 6, '...')); ?></span>
                </nav>

                <!-- Article Header -->
                <div class="single-blog-header">
                    <h1 class="single-blog-title"><?php echo esc_html($post_title); ?></h1>
                    <div class="single-blog-meta">
                        <span class="single-blog-meta__item">
                            <i class="fa-regular fa-user"></i>
                            <?php echo esc_html($author_name); ?>
                        </span>
                        <span class="single-blog-meta__item">
                            <i class="fa-regular fa-calendar"></i>
                            <?php echo esc_html($post_date); ?>
                        </span>
                        <span class="single-blog-meta__item">
                            <i class="fa-regular fa-clock"></i>
                            <?php echo esc_html($read_time); ?>
                        </span>
                    </div>
                </div>

                <!-- Mobile TOC -->
                <div class="single-blog-toc-mobile" id="tocMobile">
                    <button class="single-blog-toc-mobile__toggle" id="tocMobileToggle" aria-expanded="false">
                        <span class="toggle-left">
                            <i class="fa-solid fa-list"></i>
                            Mục lục
                        </span>
                        <i class="fa-solid fa-chevron-down toggle-arrow"></i>
                    </button>
                    <div class="single-blog-toc-mobile__content" id="tocMobileContent">
                        <ul class="single-blog-toc__list" id="tocListMobile">
                            <!-- Auto-generated by JS -->
                        </ul>
                    </div>
                </div>

                <!-- Article Body -->
                <div class="single-blog-body" id="articleBody">
                    <?php the_content(); ?>
                </div>

                <!-- Author Box -->
                <div class="author-box">
                    <div class="author-box-content">
                        <div class="author-avatar">
                            <img src="<?php echo esc_url($author_avatar); ?>"
                                alt="<?php echo esc_attr($author_name); ?>">
                        </div>
                        <div class="author-info">
                            <h3 class="author-name"><?php echo esc_html($author_name); ?></h3>
                            <?php if (!empty($author_bio)): ?>
                            <p class="author-bio"><?php echo esc_html($author_bio); ?></p>
                            <?php else: ?>
                            <p class="author-bio"></p>
                            <?php endif; ?>
                            <div class="author-meta">
                                <span class="meta-item">
                                    <i class="fa-solid fa-newspaper"></i>
                                    <?php echo esc_html($author_post_count); ?> bài viết
                                </span>
                                <span class="meta-item">
                                    <i class="fa-solid fa-calendar"></i>
                                    Tham gia <?php echo esc_html($author_joined); ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- FAQ Section -->
                <?php if (!empty($faqs)): ?>
                <div class="blog-faq-section" style="margin-top: 40px;">
                    <h2 class="single-blog-faq__heading">
                        <i class="fa-regular fa-circle-question" style="color:#007bf3"></i>
                        Câu hỏi thường gặp
                    </h2>
                    <div class="blog-faq-list">
                        <?php foreach ($faqs as $faq): ?>
                        <article class="blog-faq-item">
                            <h3 class="blog-faq-question">
                                <span><?php echo esc_html($faq['question']); ?></span>
                                <span class="blog-toggle-icon">
                                    <i class="fa-solid fa-chevron-down"></i>
                                </span>
                            </h3>
                            <div class="blog-faq-answer-container">
                                <div class="blog-faq-answer-content">
                                    <p class="blog-faq-answer"><?php echo esc_html($faq['answer']); ?></p>
                                </div>
                            </div>
                        </article>
                        <?php endforeach; ?>
                    </div>
                </div>
                <?php endif; ?>

                <!-- Back to Blog -->
                <div class="single-blog-back">
                    <a href="<?php echo esc_url(home_url('/blog')); ?>" class="single-blog-back__btn">
                        <i class="fa-solid fa-arrow-left"></i>
                        Quay lại Blog
                    </a>
                </div>

            </article>
        </div>
    </div>
</section>

<!-- ══════════════════════════════════════════
     RELATED ARTICLES
══════════════════════════════════════════ -->
<?php if ($related_query->have_posts()): ?>
<section class="single-blog-related">
    <div class="wrapper">
        <h2 class="single-blog-related__heading">Bài viết liên quan</h2>
        <p class="single-blog-related__desc">Tiếp tục khám phá các kiến thức về proxy, VPN và thu thập dữ liệu</p>

        <div class="single-blog-related__grid">
            <?php while ($related_query->have_posts()):
                            $related_query->the_post(); ?>
            <?php
                            $rel_id = get_the_ID();
                            $rel_thumb = get_the_post_thumbnail_url($rel_id, 'medium_large');
                            if (!$rel_thumb)
                                $rel_thumb = get_template_directory_uri() . '/images/placeholder.png';
                            $rel_excerpt = wp_trim_words(get_the_excerpt() ?: get_the_content(), 20, '...');
                            $rel_date = get_the_date('j \t\h\á\n\g n, Y');
                            $rel_time = vp_single_read_time($rel_id);
                            ?>
            <div class="related-card">
                <a href="<?php echo esc_url(get_permalink()); ?>" class="related-card__link">
                    <div class="related-card__image-wrap">
                        <img src="<?php echo esc_url($rel_thumb); ?>" alt="<?php echo esc_attr(get_the_title()); ?>"
                            class="related-card__image" loading="lazy">
                    </div>
                    <div class="related-card__body">
                        <h3 class="related-card__title"><?php echo esc_html(get_the_title()); ?></h3>
                        <p class="related-card__excerpt"><?php echo esc_html(wp_strip_all_tags($rel_excerpt)); ?></p>
                        <div class="related-card__meta">
                            <span class="related-card__date">
                                <i class="fa-regular fa-calendar"></i>
                                <?php echo esc_html($rel_date); ?>
                            </span>
                            <span class="related-card__read-time">
                                <i class="fa-regular fa-clock"></i>
                                <?php echo esc_html($rel_time); ?>
                            </span>
                        </div>
                    </div>
                </a>
            </div>
            <?php endwhile;
                        wp_reset_postdata(); ?>
        </div>
    </div>
</section>
<?php endif; ?>

<?php endwhile; endif; ?>

<?php get_footer(); ?>